// ============================================================
//  WebCraft Studio — main.js
//  ⚠️  DO NOT EDIT THIS FILE unless you know JavaScript.
//      It powers the sliders, navigation, and animations.
// ============================================================

document.addEventListener('DOMContentLoaded', () => {

  // ─── NAV SCROLL ─────────────────────────────────────────
  const nav = document.getElementById('nav');
  window.addEventListener('scroll', () => {
    nav.classList.toggle('scrolled', window.scrollY > 40);
  });

  // ─── HAMBURGER MENU ──────────────────────────────────────
  const hamburger = document.getElementById('hamburger');
  const navLinks  = document.querySelector('.nav-links');
  if (hamburger) {
    hamburger.addEventListener('click', () => {
      navLinks.classList.toggle('open');
    });
  }

  // ─── BUILD SLIDERS FROM websiteData ──────────────────────
  // Only build if websiteData is defined (it's loaded from data/websites.js)
  if (typeof websiteData === 'undefined') return;

  const categories = ['healthcare', 'business', 'food', 'clothing'];

  categories.forEach(cat => {
    const slider    = document.getElementById(`slider-${cat}`);
    const dotsWrap  = document.getElementById(`dots-${cat}`);
    if (!slider || !dotsWrap) return;

    const items = websiteData[cat] || [];
    if (!items.length) return;

    // Build slides
    items.forEach(site => {
      const slide = document.createElement('div');
      slide.className = 'slide';
      slide.innerHTML = `
        <img src="${site.image}" alt="${site.name}" loading="lazy"/>
        <div class="slide-overlay">
          <h4>${site.name}</h4>
          <p>${site.desc}</p>
        </div>`;
      slider.appendChild(slide);
    });

    // Build dots
    let current = 0;
    const dots  = [];

    items.forEach((_, i) => {
      const d = document.createElement('span');
      d.className = 'dot' + (i === 0 ? ' active' : '');
      d.addEventListener('click', () => goTo(i));
      dotsWrap.appendChild(d);
      dots.push(d);
    });

    function goTo(index) {
      current = (index + items.length) % items.length;
      slider.style.transform = `translateX(-${current * 100}%)`;
      dots.forEach((d, i) => d.classList.toggle('active', i === current));
    }

    // Auto-scroll every 3 seconds
    let timer = setInterval(() => goTo(current + 1), 3000);

    // Pause on hover
    slider.parentElement.addEventListener('mouseenter', () => clearInterval(timer));
    slider.parentElement.addEventListener('mouseleave', () => {
      timer = setInterval(() => goTo(current + 1), 3000);
    });
  });

  // ─── SCROLL FADE-IN ──────────────────────────────────────
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(e => {
      if (e.isIntersecting) {
        e.target.style.opacity    = '1';
        e.target.style.transform  = 'translateY(0)';
      }
    });
  }, { threshold: 0.1 });

  document.querySelectorAll('.category-block, .price-card, .step, .info-card').forEach(el => {
    el.style.opacity   = '0';
    el.style.transform = 'translateY(24px)';
    el.style.transition = 'opacity .6s ease, transform .6s ease';
    observer.observe(el);
  });

});
